<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <AssemblyName>Dynasty.Carrington.Blake.Web.Client</AssemblyName>
    <RootNamespace>Dynasty.Carrington.Blake.Web.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication"/>
    <PackageReference Include="MudBlazor"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Web.Shared\Web.Shared.csproj" />
  </ItemGroup>

</Project>
