<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Dynasty.Carrington.Krystle.Application</AssemblyName>
    <RootNamespace>Dynasty.Carrington.Krystle.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj"/>
  </ItemGroup>

</Project>
