<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="MudBlazor"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dynasty.Carrington.Blake.Infrastructure.Database\Dynasty.Carrington.Blake.Infrastructure.Database.csproj"/>
    <ProjectReference Include="..\Dynasty.Carrington.Blake.Application\Dynasty.Carrington.Blake.Application.csproj"/>
    <ProjectReference Include="..\Dynasty.Carrington.ServiceDefaults\Dynasty.Carrington.ServiceDefaults.csproj"/>
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
