<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Dynasty.Carrington.Krystle.Domain</AssemblyName>
    <RootNamespace>Dynasty.Carrington.Krystle.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Dynasty.Carrington.Core\Dynasty.Carrington.Core.csproj"/>
  </ItemGroup>

</Project>
