<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Dynasty.Carrington.Krystle.Infrastructure</AssemblyName>
    <RootNamespace>Dynasty.Carrington.Krystle.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj"/>
  </ItemGroup>

</Project>
