<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Dynasty_Carrington_Blake_Web-17f3ce76-2407-4cb6-8633-6da6fdfca4b7</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <AssemblyName>Dynasty.Carrington.Blake.Web</AssemblyName>
    <RootNamespace>Dynasty.Carrington.Blake.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Web.Shared\Web.Shared.csproj" />
    <ProjectReference Include="..\Web.Client\Web.Client.csproj"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server"/>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
